site_name: FitTrack Docs
site_description: Documentación oficial del proyecto FitTrack
site_author: Alejandro
theme:
  name: material

nav:
  - Inicio: index.md
  - Arquitectura: arquitectura.md
  - Requisitos: requisitos.md
  - Decisiones técnicas: decisiones.md
  - MVP: mvp.md
  - MVP Frontend: frontend-mvp.md
  - DEW Frontend: dew-frontend.md
  - Auditoría DEW: auditoria-dew-fit-track.md
  - Backend (API): backend-api.md
  - Backend (BD): backend-bd.md
  - Presentación / Guion: presentacion-guion.md
  - Estado actual: estado-actual.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
